#! /bin/bash

## -- Title:    morphr
## -- Author:   dkeg
## -- Created:  2016

## match border colors from current colorscheme for 2wm, dwm, 2bwm
## go through and adjust the color choices as needed

usage() {
  echo "usaage: $(basename $0) <2wm|dwm|2bwm>"
  exit 1
}

## which wm
wms=( 2wm dwm 2bwm )
for wm in ${wms[@]}; do
  pid=$(pgrep -x -u $USER $wm)
  if [[ "$pid" ]]; then
    mywm=$wm
  fi
done

## grap colors from xrdb
options=$(xrdb -query|egrep '(color|ground)'|awk '{print $2}')
color=($options)
  bg=${color[0]}
  blk=${color[1]}
  bblk=${color[15]}
  red=${color[2]}
  grn=${color[9]}
  ylw=${color[10]}
  blu=${color[11]}
  mag=${color[12]}
  cyn=${color[13]}
  wht=${color[14]}
  fg=${color[17]}

  #output order (bg,0,1,10,11,12,13,14,15,2,3,4,5,6,7,8,9,fg)

## 2wm - required to log out and back in
2w() {
  ## paths - update as needed
  dir=$HOME/git/2wm
  file=$dir/config.h

  ## grab current border colors
  CurNORM=$(awk '/\NORMCOLOR/ {gsub(/"/,"");print $3}' $file)
  CurSEL=$(awk '/\SELCOLOR/ {gsub(/"/,"");print $3}' $file)

  ## assign new colors
  NewNORM=$blk
  NewSEL=$bblk

  ## update border colors from xrdb
  sed -i "s/$CurNORM/"$NewNORM"/;
          s/$CurSEL/"$NewSEL"/" $file

  ## compile
  cd $dir && make && sudo make install && cd
}

## dwm - required to log out and back in
## or do this
## https://wiki.archlinux.org/index.php/dwm#Restart_dwm_without_logging_out_or_closing_programs
## same will work for 2wm
dw() {
  ## paths - update as needed
  dir=$HOME/git/dwm
  file=$dir/config.h

  ## assign new colors
  NewbgNORM=$blk
  NewbdrNORM=$bblk
  NewfgNORM=$wht
  NewfgFOCUS=$wht
  NewbgFOCUS=$blu

  ## grab current border colors
  ## Note that I changed the naming to sensible labels
  ## old labels: col_gray1,col_gray2,col_gray3,col_gray4,col_cyan - Really?¬
  ## let's change those for you to labels that mean something
  check=$(cat $file|grep "bg_norm")
  if [[ ! "$check" ]]; then
      sed -i "s/"col_gray1"/"bg_norm"/;
              s/"col_gray2"/"bdr_norm"/;
              s/"col_gray3"/"fg_norm"/;
              s/"col_gray4"/"fg_focus"/;
              s/"col_cyan"/"bg_focus"/g" $file
  fi

  CurbgNORM=$(awk '/\char bg_norm/ {gsub(/"/,"");gsub(/;/,"");print $6}' $file)
  CurbdrNORM=$(awk '/\char bdr_norm/ {gsub(/"/,"");gsub(/;/,"");print $6}' $file)
  CurfgNORM=$(awk '/\char fg_norm/ {gsub(/"/,"");gsub(/;/,"");print $6}' $file)
  CurfgFOCUS=$(awk '/\char fg_focus/ {gsub(/"/,"");gsub(/;/,"");print $6}' $file)
  CurbgFOCUS=$(awk '/\char bg_focus/ {gsub(/"/,"");gsub(/;/,"");print $6}' $file)

  ## update border colors from xrdb
  sed -i "s/$CurbgNORM/"$NewbgNORM"/;
          s/$CurbdrNORM/"$NewbdrNORM"/;
          s/$CurfgNORM/"$NewfgNORM"/;
          s/$CurfgFOCUS/"$NewfgFOCUS"/;
          s/$CurbgFOCUS/"$NewbgFOCUS"/" $file

  ## compile
  cd $dir && make && sudo make install && cd
}

## 2bwm - reloads in place
2b() {
  ## paths - update as needed
  dir=$HOME/git/2bwm
  file=$dir/config.h

  # wm border color options
  foc=$bblk
  unfoc=$blk
  fixc=$red
  unkil=$cyn
  fixunk=$mag
  outr=$blk
  emp=$bg

  # take the colors from the config.h and place into an array
  wmcol=$(cat $file|awk '/\*colors/ {print $6}'|cut -d '}' -f1|awk '{gsub(/"/," ");for (i=2;i<=14;i=i+2) print $i}')
  arr=($wmcol)

  # action; set the new colors}
  sed -i "s/${arr[0]}/"$foc"/;
          s/${arr[1]}/"$unfoc"/;
          s/${arr[2]}/"$fixc"/;
          s/${arr[3]}/"$unkil"/;
          s/${arr[4]}/"$fixunk"/;
          s/${arr[5]}/"$outr"/;
          s/${arr[6]}/"$emp"/" $file

  ## compile
  cd $dir && make && sudo make install && cd

  ## reload 
  xdotool key "super+ctrl+r"
} 

case $mywm in
     2wm) 2w ;;
     dwm) dw ;;
    2bwm) 2b ;;
       *) echo "You're not runnning a compatible wm. Exiting"
          usage ;;
esac

## end file
