#! /bin/bash

## morph
## match border colors from current colorscheme for 2wm, dwm, 2bwm
## go through and adjust the color choices as needed
## dkeg 2016

## which wm
wms=( 2wm dwm 2bwm )
for wm in ${wms[@]}; do
  pid=$(pgrep -x -u $USER $wm)
  if [[ "$pid" ]]; then
    mywm=$wm
  fi
done

## 2wm - required to log out and back in
2w() {
  ## paths - update as needed
  dir=$HOME/git/2wm
  file=$dir/config.h

  ## grab current border colors
  CurNORM=$(awk '/\NORMCOLOR/ {gsub(/"/,"");print $3}' $file)
  CurSEL=$(awk '/\SELCOLOR/ {gsub(/"/,"");print $3}' $file)

  ## take new colors from xrdb
  NewNORM=$(xrdb -query|awk '/\*color0/ {print $2}')
  NewSEL=$(xrdb -query|awk '/\*color8/ {print $2}')

  ## update border colors from xrdb
  sed -i "s/$CurNORM/"$NewNORM"/;
          s/$CurSEL/"$NewSEL"/" $file

  ## compile
  cd $dir && make && sudo make install && cd
}

## dwm - required to log out and back in
dw() {
  ## paths - update as needed
  dir=$HOME/git/dwm
  file=$dir/config.h

  ## take new colors from xrdb
  NewbgNORM=$(xrdb -query|awk '/\*color0/ {print $2}')
  NewbdrNORM=$(xrdb -query|awk '/\*color8/ {print $2}')
  NewfgNORM=$(xrdb -query|awk '/\*color7/ {print $2}')
  NewfgFOCUS=$(xrdb -query|awk '/\*color7/ {print $2}')
  NewbgFOCUS=$(xrdb -query|awk '/\*color4/ {print $2}')

  ## grab current border colors
  CurbgNORM=$(awk '/\char bg_norm/ {gsub(/"/,"");gsub(/;/,"");print $6}' $file)
  CurbdrNORM=$(awk '/\char bdr_norm/ {gsub(/"/,"");gsub(/;/,"");print $6}' $file)
  CurfgNORM=$(awk '/\char fg_norm/ {gsub(/"/,"");gsub(/;/,"");print $6}' $file)
  CurfgFOCUS=$(awk '/\char fg_focus/ {gsub(/"/,"");gsub(/;/,"");print $6}' $file)
  CurbgFOCUS=$(awk '/\char bg_focus/ {gsub(/"/,"");gsub(/;/,"");print $6}' $file)

  ## update border colors from xrdb
  sed -i "s/$CurbgNORM/"$NewbgNORM"/;
          s/$CurbdrNORM/"$NewbdrNORM"/;
          s/$CurfgNORM/"$NewfgNORM"/;
          s/$CurfgFOCUS/"$NewfgFOCUS"/;
          s/$CurbgFOCUS/"$NewbgFOCUS"/" $file

  ## compile
  cd $dir && make && sudo make install && cd
}

## 2bwm - reloads in place
2b() {
  ## paths - update as needed
  dir=$HOME/git/2bwm
  file=$dir/config.h

  # wm border color options
  foc=$(xrdb -query|awk '/\*color8/ {print $2}')
  unfoc=$(xrdb -query|awk '/\*color0/ {print $2}')
  fixc=$(xrdb -query|awk '/\*color1/ {print $2}')
  unkil=$(xrdb -query|awk '/\*color6/ {print $2}')
  fixunk=$(xrdb -query|awk '/\*color5/ {print $2}')
  outr=$(xrdb -query|awk '/\*color0/ {print $2}')
  emp=$(xrdb -query|awk '/\*background/ {print $2}')

  # take the colors from the config.h and place into an array
  wmcol=$(cat $file|awk '/\*colors/ {print $6}'|cut -d '}' -f1|awk '{gsub(/"/," ");for (i=2;i<=14;i=i+2) printf "%s ", $i}')
  arr=($wmcol)

  # action; set the new colors}
  sed -i "s/${arr[0]}/"$foc"/;
          s/${arr[1]}/"$unfoc"/;
          s/${arr[2]}/"$fixc"/;
          s/${arr[3]}/"$unkil"/;
          s/${arr[4]}/"$fixunk"/;
          s/${arr[5]}/"$outr"/;
          s/${arr[6]}/"$emp"/" $file

  ## compile
  cd $dir && make && sudo make install && cd

  ## reload 
  xdotool key "super+ctrl+r"
} 

case $mywm in 
   2wm) 2w 
    ;;
   dwm) dw
    ;;
  2bwm) 2b
    ;;
esac

## end file
